

site_main:
    pattern:  /main
    defaults: { _controller: BuskoSiteBundle:Main:index }
   
busko_homepage:
    pattern:  /home
    defaults: { _controller: BuskoSiteBundle:Main:index }

site_route:
    pattern:  /routes
    defaults: { _controller: BuskoSiteBundle:Main:route }

site_emp:
    pattern:  /employees
    defaults: { _controller: BuskoSiteBundle:Main:emp }
    
    
site_bus:
    pattern:  /busess
    defaults: { _controller: BuskoSiteBundle:Main:bus }
    
site_branch:
    pattern:  /branches
    defaults: { _controller: BuskoSiteBundle:Main:branch }
    
    
    
