busko_message:
    resource: "@BuskoMessageBundle/Resources/config/routing.yml"
    prefix:   /

busko_style:
    resource: "@BuskoStyleBundle/Resources/config/routing.yml"
    prefix:   /

busko_journey:
    resource: "@BuskoJourneyBundle/Resources/config/routing.yml"
    prefix:   /

busko_entity:
    resource: "@BuskoEntityBundle/Resources/config/routing.yml"
    prefix:   /

busko_employee:
    resource: "@BuskoEmployeeBundle/Resources/config/routing.yml"
    prefix:   /

busko_bus:
    resource: "@BuskoBusBundle/Resources/config/routing.yml"
    prefix:   /

busko_branch:
    resource: "@BuskoBranchBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

