busko_branch_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BuskoBranchBundle:Default:index }

branch_page:
    pattern: /branchPage
    defaults: { _controller: BuskoBranchBundle:BranchPage:branchPage }

create_branch:
    pattern: /createBranch
    defaults: { _controller: BuskoBranchBundle:BranchCreation:createBranch }

submit_branch:
    pattern: /submitBranch
    defaults: { _controller: BuskoBranchBundle:BranchSubmission:submitBranch }

confirm_branch:
    pattern: /confirmBranch
    defaults: { _controller: BuskoBranchBundle:BranchConfirmation:confirmBranch }

view_branch:
    pattern: /viewBranch
    defaults: { _controller: BuskoBranchBundle:BranchView:viewBranch }
